### ISSUE TITLE
Страница профиля текущего пользователя

### ISSUE THREAD

**Issue by ArtemGolovko** [DanyGersh/social-network#1]
Добавь страницу ткущего пользователя. На не должно присутствовать  кнопки подписаться и сообщения. Вместо них должна бить кнопка редактирования профиля. Страницу редактирования профиля тоже добавь.

**Comment by DanyGersh** [comment]
mknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgsmknnninininonoonopnopnopnopofjopsfjo[sfjopdgsjopgsdopsdhjopgdsjgsdopjgsdopjgsdopjgopgjopgsdjopgdjgposjgpojgpodgsjpogjopdsgjgspojgsdopjgdsopdsgjopgjodpsgjgsdopjgs
