### ISSUE TITLE
Детальная страница поста

### ISSUE THREAD

**Issue by ArtemGolovko** [DanyGersh/social-network#4]
Добавь детальную страницу поста. Ну как в [инстаграме](https://www.instagram.com/p/CO49LcetRGI/), или что-то типа єтого.

**Comment by DanyGersh** [comment]
Это как? У нас же не инстаграм, а что-то типо твитерра

**Comment by ArtemGolovko** [comment]
Да что-то типа твитера ([пример](https://twitter.com/BBC_ua/status/1407331958070390791?s=09))

**Comment by DanyGersh** [comment]
Здесь она не нужна, ведь у нас разворачиваются комментарии. Также для этого нужно будет сделать отдельную страницу, что не есть хорошо

**Comment by DanyGersh** [comment]
Здесь она не нужна, ведь у нас разворачиваются комментарии. Также для этого нужно будет сделать отдельную страницу, что не есть хорошо
